## Análise Exploratória

### Consolidação e tipagem

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
df = pd.read_csv('Housing.csv')

In [3]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7229300521,20141013T000000,231300.0,2,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [4]:
df['date'] = pd.to_datetime(df['date'])

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  datetime64[us]
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: datetime64[us](1), float64(5), int64(15)
memory usage: 3.5 MB

In [6]:
#Convertendo a Para Metros Quadrados

converter = ['sqft_living' , 'sqft_lot', 'sqft_above', 'sqft_basement', 'sqft_living15', 'sqft_lot15']

for i in converter:
    df[i]= df[i] * 0.092903

In [7]:
df['zipcode'] = df['zipcode'].astype(str)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  datetime64[us]
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  float64
 6   sqft_lot       21613 non-null  float64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  float64
 13  sqft_basement  21613 non-null  float64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  str
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  float64
 20  sqft_lot15     21613 non-null  float64
dtypes: datetime64[us](1), float64(11), int64(8), str(1)
memory usage: 3.5 MB

In [9]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7229300521,2014-10-13,231300.0,2,1.00,109.62554,524.901950,1.0,0,0,...,7,109.62554,0.00000,1955,0,98178,47.5112,-122.257,124.49002,524.901950
1,6414100192,2014-12-09,538000.0,3,2.25,238.76071,672.803526,2.0,0,0,...,7,201.59951,37.16120,1951,1991,98125,47.7210,-122.319,157.00607,709.686017
2,5631500400,2015-02-25,180000.0,2,1.00,71.53531,929.030000,1.0,0,0,...,6,71.53531,0.00000,1933,0,98028,47.7379,-122.233,252.69616,748.983986
3,2487200875,2014-12-09,604000.0,4,3.00,182.08988,464.515000,1.0,0,0,...,7,97.54815,84.54173,1965,0,98136,47.5208,-122.393,126.34808,464.515000
4,1954400510,2015-02-18,510000.0,3,2.00,156.07704,750.656240,1.0,0,0,...,8,156.07704,0.00000,1987,0,98074,47.6168,-122.045,167.22540,697.051209

In [10]:
df.isna().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [11]:

traducao_colunas = {
    'id': 'id_imovel',
    'date': 'data',
    'price': 'preco',
    'bedrooms': 'quartos',
    'bathrooms': 'banheiros',
    'sqft_living': 'm2_area_habitavel',    
    'sqft_lot': 'm2_terreno',
    'floors': 'andares',
    'waterfront': 'vista_mar_rio',         
    'view': 'nota_vista',                  
    'condition': 'condicao_imovel',        
    'grade': 'nota_design',                
    'sqft_above': 'm2_acima_solo',          
    'sqft_basement': 'm2_porao',          
    'yr_built': 'ano_construcao',
    'yr_renovated': 'ano_renovacao',
    'zipcode': 'codigo_postal',
    'lat': 'latitude',
    'long': 'longitude',
    'sqft_living15': 'm2_area_vizinhos_15', 
    'sqft_lot15': 'm2_terreno_vizinhos_15' 
}

df_traduzido = df.rename(columns=traducao_colunas)

print(df_traduzido.columns)

Index(['id_imovel', 'data', 'preco', 'quartos', 'banheiros',
       'm2_area_habitavel', 'm2_terreno', 'andares', 'vista_mar_rio',
       'nota_vista', 'condicao_imovel', 'nota_design', 'm2_acima_solo',
       'm2_porao', 'ano_construcao', 'ano_renovacao', 'codigo_postal',
       'latitude', 'longitude', 'm2_area_vizinhos_15',
       'm2_terreno_vizinhos_15'],
      dtype='str')

## Fase 2

### Análise histórica de preços

In [12]:
df_traduzido['ano'] = df_traduzido['data'].dt.year
df_traduzido['mes'] = df_traduzido['data'].dt.month

In [13]:
df_traduzido.head()

,id_imovel,data,preco,quartos,banheiros,m2_area_habitavel,m2_terreno,andares,vista_mar_rio,nota_vista,...,m2_porao,ano_construcao,ano_renovacao,codigo_postal,latitude,longitude,m2_area_vizinhos_15,m2_terreno_vizinhos_15,ano,mes
0,7229300521,2014-10-13,231300.0,2,1.00,109.62554,524.901950,1.0,0,0,...,0.00000,1955,0,98178,47.5112,-122.257,124.49002,524.901950,2014,10
1,6414100192,2014-12-09,538000.0,3,2.25,238.76071,672.803526,2.0,0,0,...,37.16120,1951,1991,98125,47.7210,-122.319,157.00607,709.686017,2014,12
2,5631500400,2015-02-25,180000.0,2,1.00,71.53531,929.030000,1.0,0,0,...,0.00000,1933,0,98028,47.7379,-122.233,252.69616,748.983986,2015,2
3,2487200875,2014-12-09,604000.0,4,3.00,182.08988,464.515000,1.0,0,0,...,84.54173,1965,0,98136,47.5208,-122.393,126.34808,464.515000,2014,12
4,1954400510,2015-02-18,510000.0,3,2.00,156.07704,750.656240,1.0,0,0,...,0.00000,1987,0,98074,47.6168,-122.045,167.22540,697.051209,2015,2

In [14]:
df_media_anual = df_traduzido.groupby('ano')['preco'].mean().reset_index().round(2)

In [15]:
df_media_anual

    ano      preco
0  2014  539182.07
1  2015  541988.99

In [16]:
media_mensal = df_traduzido.groupby(['ano','mes'])['preco'].mean().reset_index().round(2)
media_mensal

     ano  mes      preco
0   2014    5  548080.28
1   2014    6  558002.20
2   2014    7  544788.76
3   2014    8  536445.28
4   2014    9  529253.82
5   2014   10  539031.98
6   2014   11  521961.01
7   2014   12  524461.87
8   2015    1  525870.89
9   2015    2  507851.37
10  2015    3  543977.19
11  2015    4  561837.77
12  2015    5  558126.81

In [17]:
df_2015 = df_traduzido[df_traduzido['ano'] == 2015]

df_media_mensal_2015  = df_2015.groupby('mes')['preco'].mean().reset_index().round(2)

In [18]:
df_media_mensal_2015

   mes      preco
0    1  525870.89
1    2  507851.37
2    3  543977.19
3    4  561837.77
4    5  558126.81

In [19]:
fig = px.line(df_media_mensal_2015 , x = 'mes' , y='preco', markers = True, title = 'Média de Preços Mensais 2015')
fig.show()

### Análise Localizada

In [20]:
df_traduzido['codigo_postal'].value_counts().reset_index().head()

  codigo_postal  count
0         98103    602
1         98038    590
2         98115    583
3         98052    574
4         98117    553

In [21]:
bairro_escolhido = 98103

df_bairro = df_traduzido[df_traduzido['codigo_postal'] == bairro_escolhido]

print(f'O preço médio do cep {bairro_escolhido:.2f} é R${df_bairro['preco'].mean():.2f}, o maior preco é {df_bairro['preco'].max():.2f} o menor é {df_bairro['preco'].min()} ')

O preço médio do cep 98103.00 é R$nan, o maior preco é nan o menor é nan

## Ranking de Bairros

In [22]:
media_preco_bairro = (df_traduzido.groupby('codigo_postal')['preco'].mean()
.sort_values(ascending=False)
.reset_index()
.rename(columns= {'preco' : 'Media_preco'})
.round(2)
)
media_preco_bairro

   codigo_postal  Media_preco
0          98039   2160606.60
1          98004   1355927.08
2          98040   1194230.02
3          98112   1095499.34
4          98102    901258.27
..           ...          ...
65         98148    284908.60
66         98001    280804.69
67         98032    251296.24
68         98168    240328.37
69         98002    234284.04

[70 rows x 2 columns]

In [23]:
top5 = media_preco_bairro.head(5)
top5

  codigo_postal  Media_preco
0         98039   2160606.60
1         98004   1355927.08
2         98040   1194230.02
3         98112   1095499.34
4         98102    901258.27

In [24]:
fig_top5 = px.bar(
    top5,
    x = 'Media_preco',
    y = 'codigo_postal',
    orientation='h',
    text_auto = '.3s',
    color = 'Media_preco',
    title ='Top 5 bairros com maiores preços médios'
)
fig.update_yaxes(type = 'category')
fig_top5.show()

## Fase 3

### Identificação de Outliers

In [25]:
fig_outlier= px.box(df_traduzido, y='preco' , title= 'Distribuição de Preços com Outliers', points ='outliers')
fig_outlier.show()

In [26]:
fig_hist = px.histogram(df_traduzido , x = 'preco' , nbins= 100 , title ='Distribuição de Preços')
fig_hist.show()

In [27]:
df_traduzido

,id_imovel,data,preco,quartos,banheiros,m2_area_habitavel,m2_terreno,andares,vista_mar_rio,nota_vista,...,m2_porao,ano_construcao,ano_renovacao,codigo_postal,latitude,longitude,m2_area_vizinhos_15,m2_terreno_vizinhos_15,ano,mes
0,7229300521,2014-10-13,231300.0,2,1.00,109.62554,524.901950,1.0,0,0,...,0.00000,1955,0,98178,47.5112,-122.257,124.49002,524.901950,2014,10
1,6414100192,2014-12-09,538000.0,3,2.25,238.76071,672.803526,2.0,0,0,...,37.16120,1951,1991,98125,47.7210,-122.319,157.00607,709.686017,2014,12
2,5631500400,2015-02-25,180000.0,2,1.00,71.53531,929.030000,1.0,0,0,...,0.00000,1933,0,98028,47.7379,-122.233,252.69616,748.983986,2015,2
3,2487200875,2014-12-09,604000.0,4,3.00,182.08988,464.515000,1.0,0,0,...,84.54173,1965,0,98136,47.5208,-122.393,126.34808,464.515000,2014,12
4,1954400510,2015-02-18,510000.0,3,2.00,156.07704,750.656240,1.0,0,0,...,0.00000,1987,0,98074,47.6168,-122.045,167.22540,697.051209,2015,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,2014-05-21,360000.0,3,2.50,142.14159,105.073293,3.0,0,0,...,0.00000,2009,0,98103,47.6993,-122.346,142.14159,140.190627,2014,5
21609,6600060120,2015-02-23,400000.0,4,2.50,214.60593,540.045139,2.0,0,0,...,0.00000,2014,0,98146,47.5107,-122.362,170.01249,668.901600,2015,2
21610,1523300141,2014-06-23,402101.0,2,0.75,94.76106,125.419050,2.0,0,0,...,0.00000,2009,0,98144,47.5944,-122.299,94.76106,186.456321,2014,6
21611,291310100,2015-01-16,400000.0,3,2.50,148.64480,221.852364,2.0,0,0,...,0.00000,2004,0,98027,47.5345,-122.069,130.99323,119.566161,2015,1
21612,1523300157,2014-10-15,325000.0,2,0.75,94.76106,99.963628,2.0,0,0,...,0.00000,2008,0,98144,47.5941,-122.299,94.76106,126.069371,2014,10

# Fase 4

In [28]:


import plotly.io as pio

# Força o Plotly a renderizar corretamente dentro do Jupyter Notebook
pio.renderers.default = "jupyterlab"  # ou 'notebook' se estiver usando o Jupyter clássico
pio.renderers.default = "browser"
fig_area = px.scatter(
    df_traduzido, x="m2_area_habitavel", y="preco", title="Relação preço por área"
)
fig_area.show()

Abrindo em uma sessão de navegador existente.

In [29]:

media_mensal['data_formatada'] = media_mensal['ano'].astype(str) + '-' + media_mensal['mes'].astype(str)

fig_preco = px.line(
    media_mensal,
    x='data_formatada',
    y='preco',
    title='Evolução do Preço ao Longo do Tempo',
    labels={'data_formatada': 'Período (Ano-Mês)', 'preco': 'Preço ($)'}
)
fig_preco.update_xaxes(type='category')

fig_preco.show()

Abrindo em uma sessão de navegador existente.

In [30]:
df_traduzido.head()

,id_imovel,data,preco,quartos,banheiros,m2_area_habitavel,m2_terreno,andares,vista_mar_rio,nota_vista,...,m2_porao,ano_construcao,ano_renovacao,codigo_postal,latitude,longitude,m2_area_vizinhos_15,m2_terreno_vizinhos_15,ano,mes
0,7229300521,2014-10-13,231300.0,2,1.00,109.62554,524.901950,1.0,0,0,...,0.00000,1955,0,98178,47.5112,-122.257,124.49002,524.901950,2014,10
1,6414100192,2014-12-09,538000.0,3,2.25,238.76071,672.803526,2.0,0,0,...,37.16120,1951,1991,98125,47.7210,-122.319,157.00607,709.686017,2014,12
2,5631500400,2015-02-25,180000.0,2,1.00,71.53531,929.030000,1.0,0,0,...,0.00000,1933,0,98028,47.7379,-122.233,252.69616,748.983986,2015,2
3,2487200875,2014-12-09,604000.0,4,3.00,182.08988,464.515000,1.0,0,0,...,84.54173,1965,0,98136,47.5208,-122.393,126.34808,464.515000,2014,12
4,1954400510,2015-02-18,510000.0,3,2.00,156.07704,750.656240,1.0,0,0,...,0.00000,1987,0,98074,47.6168,-122.045,167.22540,697.051209,2015,2

In [31]:
df_traduzido['preco_por_area'] = df_traduzido['preco'] / df_traduzido['m2_area_habitavel']
df_traduzido['habitavel_por_terreno'] = df_traduzido['m2_area_habitavel'] / df_traduzido['m2_terreno']

In [32]:
df_traduzido.head()

,id_imovel,data,preco,quartos,banheiros,m2_area_habitavel,m2_terreno,andares,vista_mar_rio,nota_vista,...,ano_renovacao,codigo_postal,latitude,longitude,m2_area_vizinhos_15,m2_terreno_vizinhos_15,ano,mes,preco_por_area,habitavel_por_terreno
0,7229300521,2014-10-13,231300.0,2,1.00,109.62554,524.901950,1.0,0,0,...,0,98178,47.5112,-122.257,124.49002,524.901950,2014,10,2109.909789,0.208850
1,6414100192,2014-12-09,538000.0,3,2.25,238.76071,672.803526,2.0,0,0,...,1991,98125,47.7210,-122.319,157.00607,709.686017,2014,12,2253.302061,0.354874
2,5631500400,2015-02-25,180000.0,2,1.00,71.53531,929.030000,1.0,0,0,...,0,98028,47.7379,-122.233,252.69616,748.983986,2015,2,2516.239882,0.077000
3,2487200875,2014-12-09,604000.0,4,3.00,182.08988,464.515000,1.0,0,0,...,0,98136,47.5208,-122.393,126.34808,464.515000,2014,12,3317.043210,0.392000
4,1954400510,2015-02-18,510000.0,3,2.00,156.07704,750.656240,1.0,0,0,...,0,98074,47.6168,-122.045,167.22540,697.051209,2015,2,3267.617069,0.207921

In [33]:
df_correlacao = df_traduzido.corr('pearson')
df_correlacao

,id_imovel,data,preco,quartos,banheiros,m2_area_habitavel,m2_terreno,andares,vista_mar_rio,nota_vista,...,ano_renovacao,codigo_postal,latitude,longitude,m2_area_vizinhos_15,m2_terreno_vizinhos_15,ano,mes,preco_por_area,habitavel_por_terreno
id_imovel,1.000000,0.005576,-0.016762,0.001240,0.005158,-0.012259,-0.132109,0.018524,-0.002721,0.011592,...,-0.016907,-0.008221,-0.001891,0.020798,-0.002903,-0.138798,0.010127,-0.011706,-0.005526,0.088105
data,0.005576,1.000000,-0.004357,-0.016792,-0.034410,-0.034559,0.006313,-0.022491,0.001356,-0.001800,...,-0.024509,0.001404,-0.032856,-0.007020,-0.031515,0.002566,0.853452,-0.346640,0.037970,-0.004830
preco,-0.016762,-0.004357,1.000000,0.308377,0.525136,0.702035,0.089661,0.256793,0.266370,0.397294,...,0.126434,-0.053201,0.307003,0.021626,0.585378,0.082447,0.003575,-0.010080,0.554701,0.123115
quartos,0.001240,-0.016792,0.308377,1.000000,0.515932,0.576693,0.031713,0.175466,-0.006578,0.079543,...,0.018850,-0.152754,-0.008913,0.129482,0.391666,0.029256,-0.009804,-0.001588,-0.206030,0.026657
banheiros,0.005158,-0.034410,0.525136,0.515932,1.000000,0.754665,0.087740,0.500653,0.063744,0.187737,...,0.050739,-0.203866,0.024573,0.223042,0.568634,0.087175,-0.026596,0.007392,-0.091426,0.286338
m2_area_habitavel,-0.012259,-0.034559,0.702035,0.576693,0.754665,1.000000,0.172826,0.353949,0.103818,0.284611,...,0.055363,-0.199430,0.052529,0.240223,0.756420,0.183286,-0.029038,0.011810,-0.092318,0.077223
m2_terreno,-0.132109,0.006313,0.089661,0.031713,0.087740,0.172826,1.000000,-0.005201,0.021604,0.074710,...,0.007644,-0.129574,-0.085683,0.229521,0.144608,0.718557,0.005468,-0.002369,-0.033823,-0.252697
andares,0.018524,-0.022491,0.256793,0.175466,0.500653,0.353949,-0.005201,1.000000,0.023698,0.029444,...,0.006338,-0.059121,0.049614,0.125419,0.279885,-0.011269,-0.022315,0.014005,0.003837,0.557030
vista_mar_rio,-0.002721,0.001356,0.266370,-0.006578,0.063744,0.103818,0.021604,0.023698,1.000000,0.401857,...,0.092885,0.030285,-0.014274,-0.041910,0.086463,0.030703,-0.004165,0.008132,0.193215,-0.029875
nota_vista,0.011592,-0.001800,0.397294,0.079543,0.187737,0.284611,0.074710,0.029444,0.401857,1.000000,...,0.103917,0.084827,0.006157,-0.078400,0.280439,0.072575,0.001364,-0.005638,0.220932,-0.001307
condicao_imovel,-0.023784,-0.050769,0.036361,0.028502,-0.124982,-0.058753,-0.008958,-0.263768,0.016653,0.045990,...,-0.060618,0.003026,-0.014941,-0.106500,-0.092824,-0.003406,-0.045589,0.021978,0.102344,-0.156051
nota_design,0.008130,-0.039912,0.667434,0.356978,0.664983,0.762704,0.113621,0.458183,0.082775,0.251321,...,0.014414,-0.184862,0.114084,0.198372,0.713202,0.119248,-0.030387,0.008376,0.122757,0.191771
m2_acima_solo,-0.010843,-0.027924,0.605567,0.477614,0.685342,0.876597,0.183512,0.523885,0.072075,0.167649,...,0.023285,-0.261190,-0.000816,0.343803,0.731870,0.194050,-0.023823,0.009872,-0.088620,0.051908
m2_porao,-0.005152,-0.019469,0.323816,0.303112,0.283770,0.435043,0.015286,-0.245705,0.080588,0.276947,...,0.071323,0.074845,0.110538,-0.144765,0.200355,0.017276,-0.015687,0.006035,-0.025764,0.063132
ano_construcao,0.021379,-0.000355,0.054011,0.154198,0.506019,0.318049,0.053080,0.489319,-0.026161,-0.053440,...,-0.224874,-0.346869,-0.148122,0.409356,0.326229,0.070958,0.003507,-0.006226,-0.289869,0.279186
ano_renovacao,-0.016907,-0.024509,0.126434,0.018850,0.050739,0.055363,0.007644,0.006338,0.092885,0.103917,...,1.000000,0.064357,0.029398,-0.068372,-0.002673,0.007854,-0.023707,0.012827,0.105482,-0.003397
codigo_postal,-0.008221,0.001404,-0.053201,-0.152754,-0.203866,-0.199430,-0.129574,-0.059121,0.030285,0.084827,...,0.064357,1.000000,0.267048,-0.564072,-0.279033,-0.147221,0.001189,-0.000171,0.172637,0.177860
latitude,-0.001891,-0.032856,0.307003,-0.008913,0.024573,0.052529,-0.085683,0.049614,-0.014274,0.006157,...,0.029398,0.267048,1.000000,-0.135512,0.048858,-0.086419,-0.029212,0.014961,0.472049,0.164945
longitude,0.020798,-0.007020,0.021626,0.129482,0.223042,0.240223,0.229521,0.125419,-0.041910,-0.078400,...,-0.068372,-0.564072,-0.135512,1.000000,0.334605,0.254451,0.000270,-0.008134,-0.236033,-0.204375
m2_area_vizinhos_15,-0.002903,-0.031515,0.585378,0.391666,0.568634,0.756420,0.144608,0.279885,0.086463,0.280439,...,-0.002673,-0.279033,0.048858,0.334605,1.000000,0.183192,-0.021734,0.002449,0.038560,-0.042132
m2_terreno_vizinhos_15,-0.138798,0.002566,0.082447,0.029256,0.087175,0.183286,0.718557,-0.011269,0.030703,0.072575,...,0.007854,-0.147221,-0.086419,0.254451,0.183192,1.000000,-0.000085,0.003546,-0.057516,-0.277401
ano,0.010127,0.853452,0.003575,-0.009804,-0.026596,-0.029038,0.005468,-0.022315,-0.004165,0.001364,...,-0.023707,0.001189,-0.029212,0.000270,-0.021734,-0.000085,1.000000,-0.782389,0.045522,-0.008306
mes,-0.011706,-0.346640,-0.010080,-0.001588,0.007392,0.011810,-0.002369,0.014005,0.008132,-0.005638,...,0.012827,-0.000171,0.014961,-0.008134,0.002449,0.003546,-0.782389,1.000000,-0.034689,0.009860
preco_por_area,-0.005526,0.037970,0.554701,-0.206030,-0.091426,-0.092318,-0.033823,0.003837,0.193215,0.220932,...,0.105482,0.172637,0.472049,-0.236033,0.038560,-0.057516,0.045522,-0.034689,1.000000,0.116634
habitavel_por_terreno,0.088105,-0.004830,0.123115,0.026657,0.286338,0.077223,-0.252697,0.557030,-0.029875,-0.001307,...,-0.003397,0.177860,0.164945,-0.204375,-0.042132,-0.277401,-0.008306,0.009860,0.116634,1.000000

In [34]:
df_correlacao.index

Index(['id_imovel', 'data', 'preco', 'quartos', 'banheiros',
       'm2_area_habitavel', 'm2_terreno', 'andares', 'vista_mar_rio',
       'nota_vista', 'condicao_imovel', 'nota_design', 'm2_acima_solo',
       'm2_porao', 'ano_construcao', 'ano_renovacao', 'codigo_postal',
       'latitude', 'longitude', 'm2_area_vizinhos_15',
       'm2_terreno_vizinhos_15', 'ano', 'mes', 'preco_por_area',
       'habitavel_por_terreno'],
      dtype='str')

In [35]:
#Colunas com correlação maior que 0.6 com o preço
limite = 0.6
colunas_correlacao = (df_correlacao[df_correlacao['preco'] > limite]).index.to_list()
print(colunas_correlacao)

['preco', 'm2_area_habitavel', 'nota_design', 'm2_acima_solo']

In [36]:
df_traduzido.describe()

,id_imovel,data,preco,quartos,banheiros,m2_area_habitavel,m2_terreno,andares,vista_mar_rio,nota_vista,...,ano_construcao,ano_renovacao,latitude,longitude,m2_area_vizinhos_15,m2_terreno_vizinhos_15,ano,mes,preco_por_area,habitavel_por_terreno
count,2.161300e+04,21613,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,...,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580306e+09,2014-10-29 04:38:01.959931,5.400886e+05,3.370795,2.114757,193.228925,1403.482608,1.494309,0.007542,0.234303,...,1971.005136,84.402258,47.560053,-122.213896,184.556686,1186.227835,2014.322954,6.574423,2843.363102,0.323745
min,1.000102e+06,2014-05-02 00:00:00,7.500000e+04,0.000000,0.000000,26.941870,48.309560,1.000000,0.000000,0.000000,...,1900.000000,0.000000,47.155900,-122.519000,37.068297,60.479853,2014.000000,1.000000,942.792324,0.000610
25%,2.123049e+09,2014-07-22 00:00:00,3.219500e+05,3.000000,1.750000,132.572581,468.231120,1.000000,0.000000,0.000000,...,1951.000000,0.000000,47.471000,-122.328000,138.425470,473.805300,2014.000000,4.000000,1962.172015,0.156581
50%,3.904930e+09,2014-10-16 00:00:00,4.500000e+05,3.000000,2.250000,177.444730,707.735054,1.500000,0.000000,0.000000,...,1975.000000,0.000000,47.571800,-122.230000,170.941520,707.920860,2014.000000,6.000000,2633.333151,0.247664
75%,7.308900e+09,2015-02-17 00:00:00,6.450000e+05,4.000000,2.500000,236.902650,992.947264,2.000000,0.000000,0.000000,...,1997.000000,0.000000,47.678000,-122.125000,219.251080,936.740949,2015.000000,9.000000,3426.401530,0.407547
max,9.900000e+09,2015-05-27 00:00:00,7.700000e+06,33.000000,8.000000,1257.906620,153416.205177,3.500000,1.000000,4.000000,...,2015.000000,2015.000000,47.777600,-121.315000,576.927630,80937.093600,2015.000000,12.000000,8720.266180,4.653846
std,2.876570e+09,NaN,3.671268e+05,0.930105,0.770163,85.325915,3848.089781,0.539989,0.086517,0.766318,...,29.373411,401.679240,0.138564,0.140828,63.674908,2536.640200,0.467616,3.115308,1184.682425,0.268565