## Análise Exploratória

### Consolidação e tipagem

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

#import plotly.io as pio
#pio.renderers.default = "vscode"

In [2]:
df = pd.read_csv('Housing.csv')

In [3]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7229300521,20141013T000000,231300.0,2,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [4]:
df['date'] = pd.to_datetime(df['date'])

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  datetime64[us]
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: datetime64[us](1), float64(5), int64(15)
memory usage: 3.5 MB

In [6]:
#Convertendo a Para Metros Quadrados

converter = ['sqft_living' , 'sqft_lot', 'sqft_above', 'sqft_basement', 'sqft_living15', 'sqft_lot15']

for i in converter:
    df[i]= df[i] * 0.092903

In [7]:
df['zipcode'] = df['zipcode'].astype(str)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  datetime64[us]
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  float64
 6   sqft_lot       21613 non-null  float64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  float64
 13  sqft_basement  21613 non-null  float64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  str
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  float64
 20  sqft_lot15     21613 non-null  float64
dtypes: datetime64[us](1), float64(11), int64(8), str(1)
memory usage: 3.5 MB

In [9]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7229300521,2014-10-13,231300.0,2,1.00,109.62554,524.901950,1.0,0,0,...,7,109.62554,0.00000,1955,0,98178,47.5112,-122.257,124.49002,524.901950
1,6414100192,2014-12-09,538000.0,3,2.25,238.76071,672.803526,2.0,0,0,...,7,201.59951,37.16120,1951,1991,98125,47.7210,-122.319,157.00607,709.686017
2,5631500400,2015-02-25,180000.0,2,1.00,71.53531,929.030000,1.0,0,0,...,6,71.53531,0.00000,1933,0,98028,47.7379,-122.233,252.69616,748.983986
3,2487200875,2014-12-09,604000.0,4,3.00,182.08988,464.515000,1.0,0,0,...,7,97.54815,84.54173,1965,0,98136,47.5208,-122.393,126.34808,464.515000
4,1954400510,2015-02-18,510000.0,3,2.00,156.07704,750.656240,1.0,0,0,...,8,156.07704,0.00000,1987,0,98074,47.6168,-122.045,167.22540,697.051209

In [10]:
df.isna().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [11]:

traducao_colunas = {
    'id': 'id_imovel',
    'date': 'data',
    'price': 'preco',
    'bedrooms': 'quartos',
    'bathrooms': 'banheiros',
    'sqft_living': 'm2_area_habitavel',    
    'sqft_lot': 'm2_terreno',
    'floors': 'andares',
    'waterfront': 'vista_mar_rio',         
    'view': 'nota_vista',                  
    'condition': 'condicao_imovel',        
    'grade': 'nota_design',                
    'sqft_above': 'm2_acima_solo',          
    'sqft_basement': 'm2_porao',          
    'yr_built': 'ano_construcao',
    'yr_renovated': 'ano_renovacao',
    'zipcode': 'codigo_postal',
    'lat': 'latitude',
    'long': 'longitude',
    'sqft_living15': 'm2_area_vizinhos_15', 
    'sqft_lot15': 'm2_terreno_vizinhos_15' 
}

df_traduzido = df.rename(columns=traducao_colunas)

print(df_traduzido.columns)

Index(['id_imovel', 'data', 'preco', 'quartos', 'banheiros',
       'm2_area_habitavel', 'm2_terreno', 'andares', 'vista_mar_rio',
       'nota_vista', 'condicao_imovel', 'nota_design', 'm2_acima_solo',
       'm2_porao', 'ano_construcao', 'ano_renovacao', 'codigo_postal',
       'latitude', 'longitude', 'm2_area_vizinhos_15',
       'm2_terreno_vizinhos_15'],
      dtype='str')

## Fase 2

### Análise histórica de preços

In [12]:
df_traduzido['ano'] = df_traduzido['data'].dt.year
df_traduzido['mes'] = df_traduzido['data'].dt.month

In [13]:
df_traduzido.head()

,id_imovel,data,preco,quartos,banheiros,m2_area_habitavel,m2_terreno,andares,vista_mar_rio,nota_vista,...,m2_porao,ano_construcao,ano_renovacao,codigo_postal,latitude,longitude,m2_area_vizinhos_15,m2_terreno_vizinhos_15,ano,mes
0,7229300521,2014-10-13,231300.0,2,1.00,109.62554,524.901950,1.0,0,0,...,0.00000,1955,0,98178,47.5112,-122.257,124.49002,524.901950,2014,10
1,6414100192,2014-12-09,538000.0,3,2.25,238.76071,672.803526,2.0,0,0,...,37.16120,1951,1991,98125,47.7210,-122.319,157.00607,709.686017,2014,12
2,5631500400,2015-02-25,180000.0,2,1.00,71.53531,929.030000,1.0,0,0,...,0.00000,1933,0,98028,47.7379,-122.233,252.69616,748.983986,2015,2
3,2487200875,2014-12-09,604000.0,4,3.00,182.08988,464.515000,1.0,0,0,...,84.54173,1965,0,98136,47.5208,-122.393,126.34808,464.515000,2014,12
4,1954400510,2015-02-18,510000.0,3,2.00,156.07704,750.656240,1.0,0,0,...,0.00000,1987,0,98074,47.6168,-122.045,167.22540,697.051209,2015,2

In [14]:
df_media_anual = df_traduzido.groupby('ano')['preco'].mean().reset_index().round(2)

In [15]:
df_media_anual

    ano      preco
0  2014  539182.07
1  2015  541988.99

In [16]:
media_mensal = df_traduzido.groupby(['ano','mes'])['preco'].mean().reset_index().round(2)
media_mensal

     ano  mes      preco
0   2014    5  548080.28
1   2014    6  558002.20
2   2014    7  544788.76
3   2014    8  536445.28
4   2014    9  529253.82
5   2014   10  539031.98
6   2014   11  521961.01
7   2014   12  524461.87
8   2015    1  525870.89
9   2015    2  507851.37
10  2015    3  543977.19
11  2015    4  561837.77
12  2015    5  558126.81

In [17]:
df_2015 = df_traduzido[df_traduzido['ano'] == 2015]

df_media_mensal_2015  = df_2015.groupby('mes')['preco'].mean().reset_index().round(2)

In [18]:
df_media_mensal_2015

   mes      preco
0    1  525870.89
1    2  507851.37
2    3  543977.19
3    4  561837.77
4    5  558126.81

In [19]:
fig = px.line(df_media_mensal_2015 , x = 'mes' , y='preco', markers = True, title = 'Média de Preços Mensais 2015')
fig.show()

### Análise Localizada

In [20]:
df_traduzido['codigo_postal'].value_counts().reset_index().head()

  codigo_postal  count
0         98103    602
1         98038    590
2         98115    583
3         98052    574
4         98117    553

In [21]:
bairro_escolhido ='98103'
#intevalo de anos:
ano_ini , ano_fim = 2014, 2015


df_bairro = df_traduzido[(df_traduzido['codigo_postal'] == bairro_escolhido) & (df_traduzido['ano'].between(ano_ini, ano_fim)) ]

print(f'O preço médio do cep {bairro_escolhido} é R${df_bairro['preco'].mean():.2f}, o maior preco é {df_bairro['preco'].max():.2f} o menor é {df_bairro['preco'].min()} ')

O preço médio do cep 98103 é R$584919.21, o maior preco é 1695000.00 o menor é 238000.0

## Ranking de Bairros

In [22]:
media_preco_bairro = (df_traduzido.groupby('codigo_postal')['preco'].mean()
.sort_values(ascending=False)
.reset_index()
.rename(columns= ({'preco' : 'Media_preco','codigo_postal' :'Bairro' }))
.round(2)
)
media_preco_bairro

   Bairro  Media_preco
0   98039   2160606.60
1   98004   1355927.08
2   98040   1194230.02
3   98112   1095499.34
4   98102    901258.27
..    ...          ...
65  98148    284908.60
66  98001    280804.69
67  98032    251296.24
68  98168    240328.37
69  98002    234284.04

[70 rows x 2 columns]

In [23]:
top5 = media_preco_bairro.head(5)
top5

  Bairro  Media_preco
0  98039   2160606.60
1  98004   1355927.08
2  98040   1194230.02
3  98112   1095499.34
4  98102    901258.27

In [24]:
fig_top5 = px.bar(
    top5,
    x = 'Media_preco',
    y = 'Bairro',
    orientation='h',
    text_auto = '.3s',
    color = 'Media_preco',
    title ='Top 5 bairros com maiores preços médios'
)
fig_top5.update_yaxes(type = 'category')
fig_top5.show()

## Fase 3

### Identificação de Outliers

In [25]:
fig_outlier= px.box(df_traduzido, y='preco' , title= 'Distribuição de Preços com Outliers', points ='outliers')
fig_outlier.show()

In [26]:
fig_hist = px.histogram(df_traduzido , x = 'preco' , nbins= 100 , title ='Distribuição de Preços')
fig_hist.show()

In [27]:
df_traduzido

,id_imovel,data,preco,quartos,banheiros,m2_area_habitavel,m2_terreno,andares,vista_mar_rio,nota_vista,...,m2_porao,ano_construcao,ano_renovacao,codigo_postal,latitude,longitude,m2_area_vizinhos_15,m2_terreno_vizinhos_15,ano,mes
0,7229300521,2014-10-13,231300.0,2,1.00,109.62554,524.901950,1.0,0,0,...,0.00000,1955,0,98178,47.5112,-122.257,124.49002,524.901950,2014,10
1,6414100192,2014-12-09,538000.0,3,2.25,238.76071,672.803526,2.0,0,0,...,37.16120,1951,1991,98125,47.7210,-122.319,157.00607,709.686017,2014,12
2,5631500400,2015-02-25,180000.0,2,1.00,71.53531,929.030000,1.0,0,0,...,0.00000,1933,0,98028,47.7379,-122.233,252.69616,748.983986,2015,2
3,2487200875,2014-12-09,604000.0,4,3.00,182.08988,464.515000,1.0,0,0,...,84.54173,1965,0,98136,47.5208,-122.393,126.34808,464.515000,2014,12
4,1954400510,2015-02-18,510000.0,3,2.00,156.07704,750.656240,1.0,0,0,...,0.00000,1987,0,98074,47.6168,-122.045,167.22540,697.051209,2015,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,2014-05-21,360000.0,3,2.50,142.14159,105.073293,3.0,0,0,...,0.00000,2009,0,98103,47.6993,-122.346,142.14159,140.190627,2014,5
21609,6600060120,2015-02-23,400000.0,4,2.50,214.60593,540.045139,2.0,0,0,...,0.00000,2014,0,98146,47.5107,-122.362,170.01249,668.901600,2015,2
21610,1523300141,2014-06-23,402101.0,2,0.75,94.76106,125.419050,2.0,0,0,...,0.00000,2009,0,98144,47.5944,-122.299,94.76106,186.456321,2014,6
21611,291310100,2015-01-16,400000.0,3,2.50,148.64480,221.852364,2.0,0,0,...,0.00000,2004,0,98027,47.5345,-122.069,130.99323,119.566161,2015,1
21612,1523300157,2014-10-15,325000.0,2,0.75,94.76106,99.963628,2.0,0,0,...,0.00000,2008,0,98144,47.5941,-122.299,94.76106,126.069371,2014,10

# Fase 4

In [28]:

fig_area = px.scatter(
    df_traduzido, x="m2_area_habitavel", y="preco", title="Relação preço por área"
)
fig_area.show()

In [29]:

media_mensal['data_formatada'] = media_mensal['ano'].astype(str) + '-' + media_mensal['mes'].astype(str)

fig_preco = px.line(
    media_mensal,
    x='data_formatada',
    y='preco',
    title='Evolução do Preço ao Longo do Tempo',
    labels={'data_formatada': 'Período (Ano-Mês)', 'preco': 'Preço ($)'}
)
fig_preco.update_xaxes(type='category')

fig_preco.show()

In [30]:
df_traduzido.head()

,id_imovel,data,preco,quartos,banheiros,m2_area_habitavel,m2_terreno,andares,vista_mar_rio,nota_vista,...,m2_porao,ano_construcao,ano_renovacao,codigo_postal,latitude,longitude,m2_area_vizinhos_15,m2_terreno_vizinhos_15,ano,mes
0,7229300521,2014-10-13,231300.0,2,1.00,109.62554,524.901950,1.0,0,0,...,0.00000,1955,0,98178,47.5112,-122.257,124.49002,524.901950,2014,10
1,6414100192,2014-12-09,538000.0,3,2.25,238.76071,672.803526,2.0,0,0,...,37.16120,1951,1991,98125,47.7210,-122.319,157.00607,709.686017,2014,12
2,5631500400,2015-02-25,180000.0,2,1.00,71.53531,929.030000,1.0,0,0,...,0.00000,1933,0,98028,47.7379,-122.233,252.69616,748.983986,2015,2
3,2487200875,2014-12-09,604000.0,4,3.00,182.08988,464.515000,1.0,0,0,...,84.54173,1965,0,98136,47.5208,-122.393,126.34808,464.515000,2014,12
4,1954400510,2015-02-18,510000.0,3,2.00,156.07704,750.656240,1.0,0,0,...,0.00000,1987,0,98074,47.6168,-122.045,167.22540,697.051209,2015,2

In [31]:
df_traduzido['habitavel_por_terreno'] = df_traduzido['m2_area_habitavel'] / df_traduzido['m2_terreno']
df_traduzido['idade_efetiva'] = df_traduzido['ano'] - df_traduzido[['ano_construcao','ano_renovacao']].max(axis=1)
df_traduzido['total_comodos'] = df_traduzido['quartos'] + df_traduzido['banheiros']
df_traduzido['foi_renovado'] = (df_traduzido['ano_renovacao'] > 0).astype(int)

In [32]:
cols_tirar = ['id_imovel', 'data' , 'codigo_postal']
df_correlacao_pearson = df_traduzido.drop(columns= cols_tirar).corr('pearson')


df_correlacao_pearson

,preco,quartos,banheiros,m2_area_habitavel,m2_terreno,andares,vista_mar_rio,nota_vista,condicao_imovel,nota_design,...,latitude,longitude,m2_area_vizinhos_15,m2_terreno_vizinhos_15,ano,mes,habitavel_por_terreno,idade_efetiva,total_comodos,foi_renovado
preco,1.000000,0.308377,0.525136,0.702035,0.089661,0.256793,0.266370,0.397294,0.036361,0.667434,...,0.307003,0.021626,0.585378,0.082447,0.003575,-0.010080,0.123115,-0.105671,0.466325,0.126092
quartos,0.308377,1.000000,0.515932,0.576693,0.031713,0.175466,-0.006578,0.079543,0.028502,0.356978,...,-0.008913,0.129482,0.391666,0.029256,-0.009804,-0.001588,0.026657,-0.165650,0.895500,0.018562
banheiros,0.525136,0.515932,1.000000,0.754665,0.087740,0.500653,0.063744,0.187737,-0.124982,0.664983,...,0.024573,0.223042,0.568634,0.087175,-0.026596,0.007392,0.286338,-0.537469,0.843270,0.050260
m2_area_habitavel,0.702035,0.576693,0.754665,1.000000,0.172826,0.353949,0.103818,0.284611,-0.058753,0.762704,...,0.052529,0.240223,0.756420,0.183286,-0.029038,0.011810,0.077223,-0.344135,0.753931,0.055094
m2_terreno,0.089661,0.031713,0.087740,0.172826,1.000000,-0.005201,0.021604,0.074710,-0.008958,0.113621,...,-0.085683,0.229521,0.144608,0.718557,0.005468,-0.002369,-0.252697,-0.052809,0.065483,0.007745
andares,0.256793,0.175466,0.500653,0.353949,-0.005201,1.000000,0.023698,0.029444,-0.263768,0.458183,...,0.049614,0.125419,0.279885,-0.011269,-0.022315,0.014005,0.557030,-0.505651,0.370210,0.006260
vista_mar_rio,0.266370,-0.006578,0.063744,0.103818,0.021604,0.023698,1.000000,0.401857,0.016653,0.082775,...,-0.014274,-0.041910,0.086463,0.030703,-0.004165,0.008132,-0.029875,0.000469,0.028991,0.093294
nota_vista,0.397294,0.079543,0.187737,0.284611,0.074710,0.029444,0.401857,1.000000,0.045990,0.251321,...,0.006157,-0.078400,0.280439,0.072575,0.001364,-0.005638,-0.001307,0.018282,0.147448,0.104062
condicao_imovel,0.036361,0.028502,-0.124982,-0.058753,-0.008958,-0.263768,0.016653,0.045990,1.000000,-0.144674,...,-0.014941,-0.106500,-0.092824,-0.003406,-0.045589,0.021978,-0.156051,0.395525,-0.047051,-0.060139
nota_design,0.667434,0.356978,0.664983,0.762704,0.113621,0.458183,0.082775,0.251321,-0.144674,1.000000,...,0.114084,0.198372,0.713202,0.119248,-0.030387,0.008376,0.191771,-0.461180,0.569477,0.014008
m2_acima_solo,0.605567,0.477614,0.685342,0.876597,0.183512,0.523885,0.072075,0.167649,-0.158214,0.755923,...,-0.000816,0.343803,0.731870,0.194050,-0.023823,0.009872,0.051908,-0.436188,0.655748,0.023178
m2_porao,0.323816,0.303112,0.283770,0.435043,0.015286,-0.245705,0.080588,0.276947,0.174105,0.168392,...,0.110538,-0.144765,0.200355,0.017276,-0.015687,0.006035,0.063132,0.101985,0.337620,0.070963
ano_construcao,0.054011,0.154198,0.506019,0.318049,0.053080,0.489319,-0.026161,-0.053440,-0.361417,0.446963,...,-0.148122,0.409356,0.326229,0.070958,0.003507,-0.006226,0.279186,-0.909652,0.359654,-0.225195
ano_renovacao,0.126434,0.018850,0.050739,0.055363,0.007644,0.006338,0.092885,0.103917,-0.060618,0.014414,...,0.029398,-0.068372,-0.002673,0.007854,-0.023707,0.012827,-0.003397,-0.164923,0.038189,0.999968
latitude,0.307003,-0.008913,0.024573,0.052529,-0.085683,0.049614,-0.014274,0.006157,-0.014941,0.114084,...,1.000000,-0.135512,0.048858,-0.086419,-0.029212,0.014961,0.164945,0.135043,0.007174,0.029350
longitude,0.021626,0.129482,0.223042,0.240223,0.229521,0.125419,-0.041910,-0.078400,-0.106500,0.198372,...,-0.135512,1.000000,0.334605,0.254451,0.000270,-0.008134,-0.204375,-0.382872,0.197125,-0.068378
m2_area_vizinhos_15,0.585378,0.391666,0.568634,0.756420,0.144608,0.279885,0.086463,0.280439,-0.092824,0.713202,...,0.048858,0.334605,1.000000,0.183192,-0.021734,0.002449,-0.042132,-0.324856,0.541184,-0.002755
m2_terreno_vizinhos_15,0.082447,0.029256,0.087175,0.183286,0.718557,-0.011269,0.030703,0.072575,-0.003406,0.119248,...,-0.086419,0.254451,0.183192,1.000000,-0.000085,0.003546,-0.277401,-0.070204,0.063648,0.007920
ano,0.003575,-0.009804,-0.026596,-0.029038,0.005468,-0.022315,-0.004165,0.001364,-0.045589,-0.030387,...,-0.029212,0.000270,-0.021734,-0.000085,1.000000,-0.782389,-0.008306,0.022632,-0.019969,-0.023688
mes,-0.010080,-0.001588,0.007392,0.011810,-0.002369,0.014005,0.008132,-0.005638,0.021978,0.008376,...,0.014961,-0.008134,0.002449,0.003546,-0.782389,1.000000,0.009860,-0.011013,0.002844,0.012840
habitavel_por_terreno,0.123115,0.026657,0.286338,0.077223,-0.252697,0.557030,-0.029875,-0.001307,-0.156051,0.191771,...,0.164945,-0.204375,-0.042132,-0.277401,-0.008306,0.009860,1.000000,-0.296511,0.165493,-0.003696
idade_efetiva,-0.105671,-0.165650,-0.537469,-0.344135,-0.052809,-0.505651,0.000469,0.018282,0.395525,-0.461180,...,0.135043,-0.382872,-0.324856,-0.070204,0.022632,-0.011013,-0.296511,1.000000,-0.383179,-0.164049
total_comodos,0.466325,0.895500,0.843270,0.753931,0.065483,0.370210,0.028991,0.147448,-0.047051,0.569477,...,0.007174,0.197125,0.541184,0.063648,-0.019969,0.002844,0.165493,-0.383179,1.000000,0.037759
foi_renovado,0.126092,0.018562,0.050260,0.055094,0.007745,0.006260,0.093294,0.104062,-0.060139,0.014008,...,0.029350,-0.068378,-0.002755,0.007920,-0.023688,0.012840,-0.003696,-0.164049,0.037759,1.000000

In [33]:
corr_preco_pearson = df_correlacao_pearson['preco'].drop('preco').abs()
corr_preco_spearman = df_traduzido.corr('spearman')['preco'].sort_values(ascending=False).drop('preco').abs()

In [42]:
comparacao = pd.DataFrame({
    'pearson': corr_preco_pearson,
    'spearman': corr_preco_spearman
})
comparacao['diferenca'] = (comparacao['spearman'] - comparacao['pearson']).round(3)
comparacao['pearson'] = comparacao['pearson'].round(3)
comparacao['spearman'] = comparacao['spearman'].round(3)

comparacao = comparacao.reindex(
    comparacao['spearman'].abs().sort_values(ascending=False).index
)
print(comparacao)

                        pearson  spearman  diferenca
nota_design               0.667     0.658     -0.009
m2_area_habitavel         0.702     0.644     -0.058
m2_area_vizinhos_15       0.585     0.572     -0.013
m2_acima_solo             0.606     0.542     -0.064
banheiros                 0.525     0.497     -0.028
total_comodos             0.466     0.475      0.009
latitude                  0.307     0.456      0.149
quartos                   0.308     0.345      0.036
andares                   0.257     0.322      0.066
nota_vista                0.397     0.294     -0.103
habitavel_por_terreno     0.123     0.280      0.157
m2_porao                  0.324     0.252     -0.072
idade_efetiva             0.106     0.153      0.047
vista_mar_rio             0.266     0.115     -0.151
ano_renovacao             0.126     0.102     -0.025
ano_construcao            0.054     0.102      0.048
foi_renovado              0.126     0.101     -0.025
m2_terreno                0.090     0.075     -0.015
longitude                 0.022     0.064      0.042
m2_terreno_vizinhos_15    0.082     0.063     -0.020
condicao_imovel           0.036     0.018     -0.018
mes                       0.010     0.015      0.005
data                        NaN     0.011        NaN
codigo_postal               NaN     0.009        NaN
ano                       0.004     0.004      0.001
id_imovel                   NaN     0.004        NaN

In [35]:
fig_heatmap = px.imshow(
    df_correlacao_pearson,
    text_auto='.2f',            # escreve o valor em cada célula
    aspect='auto',
    color_continuous_scale='RdBu_r',   # vermelho = +, azul = -
    zmin=-1, zmax=1,            # fixa a escala de cor de -1 a 1
    title='Mapa de calor — correlação de Pearson entre variáveis'
                        )
fig_heatmap.update_layout(height=800, width=900)
fig_heatmap.show()

In [36]:
from sklearn.model_selection import train_test_split

features = [ 'm2_area_habitavel', 'nota_design', 'm2_area_vizinhos_15',
    'total_comodos', 'nota_vista', 'm2_porao',
    'habitavel_por_terreno', 'idade_efetiva', 'vista_mar_rio']

df_modelo = df_traduzido.sort_values('data').drop_duplicates('id_imovel', keep = 'last')
X = df_modelo[features].values
y = df_modelo['preco'].values


X_train, X_test,y_train,y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42
)
mu = X_train.mean(axis = 0)
sigma =X_train.std(axis= 0)

X_train_norm = (X_train - mu) / sigma
X_test_norm = (X_test - mu) / sigma

print("Média treino :", X_train_norm.mean(axis=0).round(3))
print("Desvio treino :", X_train_norm.std(axis=0).round(3))
print("\nMédia teste :", X_test_norm.mean(axis=0).round(3))

Média treino : [ 0. -0.  0.  0.  0.  0.  0.  0.  0.]
Desvio treino : [1. 1. 1. 1. 1. 1. 1. 1. 1.]

Média teste : [-0.004  0.012  0.003 -0.013  0.045 -0.009  0.017 -0.015  0.033]

In [37]:
def gerar_termos_polinomiais(X,grau):
    lista_termos = [X]
    for g in range(2 , grau+1):
        lista_termos.append(X ** g)
    return np.concatenate(lista_termos, axis =1)

X_train_poly = gerar_termos_polinomiais(X_train_norm , grau = 2)
X_test_poly  = gerar_termos_polinomiais(X_test_norm, grau =2)

print(f"Antes:  {X_train_norm.shape[1]} features")
print(f"Depois (grau 2): {X_train_poly.shape[1]} features")

Antes:  9 features
Depois (grau 2): 18 features

In [38]:
def descida_gradiente(X, y, alpha=0.01, lambda_reg=0.1, n_iter=1000):
    m, n = X.shape
    w = np.zeros(n)
    b = 0.0
    historico_custo = []
    for i in range(n_iter):

        y_pred = X @ w + b
        erro = y_pred - y

        grad_w = (X.T @ erro) / m + (lambda_reg / m) * w

        grad_b = erro.mean()

        w = w - alpha * grad_w
        b = b - alpha * grad_b

        custo = (erro**2).mean() / 2 + (lambda_reg / (2 * m)) * (w**2).sum()

        historico_custo.append(custo)
        
    return w, b, historico_custo

In [39]:
mu_y = y_train.mean()
sigma_y = y_train.std()

y_train_norm = (y_train - mu_y) / sigma_y
y_test_norm  = (y_test - mu_y) / sigma_y

In [44]:
# Executa o treinamento
w, b, historico = descida_gradiente(
    X_train_poly, y_train_norm,
    alpha=0.01, lambda_reg=0.1, n_iter=1000
)

# Plota a curva de convergência
fig_custo = px.line(y=historico, title='Convergência do custo')
fig_custo.update_xaxes(title='Iteração')
fig_custo.update_yaxes(title='Custo (escala normalizada)')
fig_custo.show()

print(f"Custo inicial: {historico[0]:.4f}")
print(f"Custo final:   {historico[-1]:.4f}")

Custo inicial: 0.5000
Custo final:   0.1599